import {
  Cactus,
  Detective,
  FlyingSaucer,
  Ghost,
  HandHeart,
  Heartbeat,
  HourglassMedium,
  Jeep,
  Knife,
  MagicWand,
  MaskSad,
  Mountains,
  Pen,
  PersonSimpleRun,
  PianoKeys,
  SmileyWink,
  Television,
  UsersThree,
  VideoCamera,
} from "@phosphor-icons/react";

export const GenreIcons = new Map([
  [12, Mountains],
  [28, PersonSimpleRun],
  [16, Pen],
  [99, VideoCamera],
  [18, MaskSad],
  [10751, UsersThree],
  [14, MagicWand],
  [36, HourglassMedium],
  [27, Ghost],
  [35, SmileyWink],
  [10752, Jeep],
  [80, Knife],
  [10749, HandHeart],
  [10402, PianoKeys],
  [9648, Detective],
  [878, FlyingSaucer],
  [53, Heartbeat],
  [10770, Television],
  [37, Cactus],
]);
